src/Entity/Fighter.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FighterRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable
 */
class Fighter
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Vich\UploadableField(mapping="fighter_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $strength;

    /**
     * @ORM\Column(type="integer")
     */
    private $intelligence;

    /**
     * @ORM\Column(type="integer")
     */
    private $pv;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $killed_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Type", inversedBy="fighters")
     */
    private $type;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Battle", mappedBy="fighter")
     */
    private $zone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Battle", mappedBy="winner_id")
     */
    private $battles;

    public function __construct()
    {
        $this->zone = new ArrayCollection();
        $this->battles = new ArrayCollection();
    }

    /**
     * @ORM\Column(type="text")
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $king;

    /**
     * @ORM\PrePersist()
     */
    public function onPrePersist()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onPreUpdate()
    {
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStrength(): ?int
    {
        return $this->strength;
    }

    public function setStrength(int $strength): self
    {
        $this->strength = $strength;

        return $this;
    }

    public function getIntelligence(): ?int
    {
        return $this->intelligence;
    }

    public function setIntelligence(int $intelligence): self
    {
        $this->intelligence = $intelligence;

        return $this;
    }

    public function getPv(): ?int
    {
        return $this->pv;
    }

    public function setPv(int $pv): self
    {
        $this->pv = $pv;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getKilledAt(): ?\DateTimeInterface
    {
        return $this->killed_at;
    }

    public function setKilledAt(?\DateTimeInterface $killed_at): self
    {
        $this->killed_at = $killed_at;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }


    /**
     * @return Collection|Battle[]
     */
    public function getZone(): Collection
    {
        return $this->zone;
    }

    public function addZone(Battle $zone): self
    {
        if (!$this->zone->contains($zone)) {
            $this->zone[] = $zone;
            $zone->addFighter($this);
        }

        return $this;
    }

    public function removeZone(Battle $zone): self
    {
        if ($this->zone->contains($zone)) {
            $this->zone->removeElement($zone);
            $zone->removeFighter($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|Battle[]
     */
    public function getBattles(): Collection
    {
        return $this->battles;
    }

    public function addBattle(Battle $battle): self
    {
        if (!$this->battles->contains($battle)) {
            $this->battles[] = $battle;
            $battle->setWinner($this);
        }

        return $this;
    }

    public function removeBattle(Battle $battle): self
    {
        if ($this->battles->contains($battle)) {
            $this->battles->removeElement($battle);
            // set the owning side to null (unless already changed)
            if ($battle->getWinner() === $this) {
                $battle->setWinner(null);
            }
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getKing(): ?bool
    {
        return $this->king;
    }

    public function setKing(?bool $king): self
    {
        $this->king = $king;

        return $this;
    }
}

src/Form/FighterType.php
<?php

namespace App\Form;

use App\Entity\Fighter;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FighterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('strength')
            ->add('intelligence')
            ->add('pv')
            ->add('type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fighter::class,
        ]);
    }
}

src/Controller/FighterController.php
<?php

namespace App\Controller;

use App\Entity\Fighter;
use App\Form\FighterType;
use App\Repository\FighterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Cocur\Slugify\Slugify;

/**
 * @Route("/fighter")
 */
class FighterController extends AbstractController
{
    /**
     * @Route   ("/", name="fighter_index", methods={"GET"})
     */
    public function index(FighterRepository $fighterRepository): Response
    {
        return $this->render('fighter/index.html.twig', [
            'fighters' => $fighterRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fighter_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $fighter = new Fighter();
        $slugify = new Slugify();
        $form = $this->createForm(FighterType::class, $fighter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $fighter->setSlug($slugify->slugify($fighter->getName()));
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fighter);
            $entityManager->flush();

            return $this->redirectToRoute('fighter_index');
        }

        return $this->render('fighter/new.html.twig', [
            'fighter' => $fighter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="fighter_show", methods={"GET"})
     */
    public function show(Fighter $fighter, FighterRepository $fighterRepository): Response
    {
        $battles = $fighterRepository->findBattles($fighter);

        return $this->render('fighter/show.html.twig', [
            'fighter' => $fighter,
            'battles' => $battles
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="fighter_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Fighter $fighter): Response
    {
        $form = $this->createForm(FighterType::class, $fighter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fighter_index');
        }

        return $this->render('fighter/edit.html.twig', [
            'fighter' => $fighter,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="fighter_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Fighter $fighter): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fighter->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fighter);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fighter_index');
    }
}

templates/fighter/_delete_form.html.twig
<hr>
<form method="post" class="mb-4" action="{{ path('fighter_delete', {'slug': fighter.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fighter.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/fighter/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fighter{% endblock %}

{% block body %}
    <h1>Edit Fighter</h1>

    {{ include('fighter/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fighter_index') }}">back to list</a>

    {{ include('fighter/_delete_form.html.twig') }}
{% endblock %}

templates/fighter/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des combattants{% endblock %}

{% block body %}

    <h1><strong style="font-size: 70px">⚔</strong>️ Liste des soldats</h1>

    <div class="table-responsive mt-1 mb-5">
        <table class="table table-bordered table-striped" id="datatable">
            <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Force</th>
                <th>Intelligence</th>
                <th>PV</th>
                <th>Race</th>
                <th>Décès</th>
                <th>Création</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for fighter in fighters %}
                <tr>
                    <td>{{ fighter.id }}</td>
                    <td>
                        {% if fighter.king == 1 %}
                            <a data-toggle="tooltip" data-placement="top" title="Vainqueur de tournoi" href="{{ path('fighter_show', {'slug': fighter.slug}) }}">
                            <strong style="font-size: 20px">👑</strong> {{ fighter.name }}
                            </a>
                        {% endif %}
                        {% if fighter.king == 0 %}
                            <a href="{{ path('fighter_show', {'slug': fighter.slug}) }}">
                                {{ fighter.name }}
                            </a>
                        {% endif %}

                    </td>
                    <td>{{ fighter.strength }}</td>
                    <td>{{ fighter.intelligence }}</td>
                    <td>{{ fighter.pv }}</td>
                    <td>
                        <span class="badge badge-success">{{ fighter.type }}</span>
                    </td>
                    <td>{{ fighter.killedAt ? fighter.killedAt|date('d-m-Y H:i:s') : '' }}</td>
                    <td>{{ fighter.createdAt ? fighter.createdAt|date('d-m-Y') : '' }}</td>
                    <td>
                        <a class="btn btn-secondary" href="{{ path('fighter_show', {'slug': fighter.slug}) }}"><i class="fas fa-eye"></i></a>
                        <a class="btn btn-primary" href="{{ path('fighter_edit', {'slug': fighter.slug}) }}"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">Aucun enregistrement trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/fighter/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fighter{% endblock %}

{% block body %}
    <h1>Create new Fighter</h1>

    {{ include('fighter/_form.html.twig') }}

    <a href="{{ path('fighter_index') }}">back to list</a>
{% endblock %}

templates/fighter/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ fighter.name }}{% endblock %}

{% block body %}
    <h1>{{ fighter.name }}</h1>

    <div class="col-md-2">
        <img src="{{ vich_uploader_asset(fighter, 'imageFile') }}" class="img-fluid">
    </div>

    <br>

    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ fighter.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ fighter.name }}</td>
            </tr>
            <tr>
                <th>Force</th>
                <td>{{ fighter.strength }}</td>
            </tr>
            <tr>
                <th>Intelligence</th>
                <td>{{ fighter.intelligence }}</td>
            </tr>
            <tr>
                <th>PV</th>
                <td>{{ fighter.pv }}</td>
            </tr>
            <tr>
                <th>Race</th>
                <td>{{ fighter.type }}</td>
            </tr>
            <tr>
                <th>Création</th>
                <td>{{ fighter.createdAt ? fighter.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modification</th>
                <td>{{ fighter.updatedAt ? fighter.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Décès</th>
                <td>{{ fighter.killedAt ? fighter.killedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <h1>Combat(s) réalisé(s)</h1>
    {% if battles == null %}
        <p>Aucun combat réalisé</p>
    {% endif %}
    {% for battle in battles %}
        <a href="{{ path('battle_show', {'id': battle.battle_id}) }}">Combat N°{{ battle.battle_id }}</a><br>
    {% endfor  %}

    <hr>


    <a href="{{ path('fighter_index') }}" class="btn btn-primary" role="button">Retour à la liste</a>

    <a class="btn btn-warning" href="{{ path('fighter_edit', {'slug': fighter.slug}) }}">Editer</a>

    {{ include('fighter/_delete_form.html.twig') }}
{% endblock %}